### PR TITLE
Fix #12: when cloning a bazar repository, create local directories

### LINKED ISSUE #12: fail to import bzr repository: subfolders are not created
see https://github.com/Masterminds/glide/issues/221

### PR DESCRIPTION
**Pull request by cyrilleverrier**

### CODE REVIEW

File: bzr.go [hunk 1]
```diff
@@ -24,6 +25,11 @@ func NewBzrRepo(remote, local string) (*BzrRepo, error) {
 	r.setRemote(remote)
 	r.setLocalPath(local)
 	r.Logger = Logger
+	
+	basePath := path.Join(r.LocalPath(), "..")
+	if _, err := os.Stat(basePath); err != nil {
+		err = os.MkdirAll(basePath, 0777)
+	}
```
Comment (mattfarina) [inline bzr.go]: Three things stand out:

1. Why isn't `bzr` creating the directory?
2. A permission of `0777` is globally writable. That's not a good permission by default.
3. Any change like this should be in the `Get()` method instead of the constructor.

**Comment by mattfarina** [comment]
Since this is linked to Glide, I think Glide should be creating the necessary higher level directories. In the test suite there is no issue creating the directories. What's the underlying problem?

**Comment by cyrilleverrier** [comment]
@mattfarina : the underlying issue is explained here: https://github.com/Masterminds/glide/issues/221

I can't use glide up to fetch the dependency `labix.org/v2/mgo`

File: bzr.go [hunk 2]
```diff
@@ -64,6 +65,12 @@ func (s BzrRepo) Vcs() Type {
 
 // Get is used to perform an initial clone of a repository.
 func (s *BzrRepo) Get() error {
+
+	basePath := path.Join(s.LocalPath(), "..")
```
Comment (mattfarina) [inline bzr.go]: Instead of `path.Join` this should be `filepath.Join` so that it handles cross platform directory separators correctly.

File: bzr.go [hunk 3]
```diff
@@ -64,6 +65,12 @@ func (s BzrRepo) Vcs() Type {
...
+	if _, err := os.Stat(basePath); err != nil {
```
Comment (mattfarina) [inline bzr.go]: The error should be checked to make sure it's a not exists error which can be done with [`os.IsNotExist(err)`](https://golang.org/pkg/os/#IsNotExist) instead or the `err != nil` section. Any other error should return an error.

File: bzr.go (hunk 2 above)
Comment (mattfarina) [inline bzr.go]: Actually, instead of using `Join` an alternative approach should be used.
```go
basePath := filepath.Dir(filepath.FromSlash(s.LocalPath()))
```

This will do 2 things:

1. It will convert the directory separator into the correct one for the OS.
2. It will let the `filepath` package figure out the parent directory. That's going to be far more well tested than doing it ourselves.

**Comment by cyrilleverrier** [comment]
@mattfarina : thanks for the valuable feedback. Would you like me to update this PR or do you want Glide to create the directories?

**Comment by mattfarina** [comment]
Thank you for the contribution!
